set nocompatible
filetype off

"set rtp+=~/.vim/vundle
"call vundle#rc()
"Bundle 'gmarik/vundle'

filetype plugin indent on

set backspace=start,eol,indent
set encoding=utf-8
set fileencodings=utf-8,cp932,euc-jp
set ignorecase
set smartcase
set incsearch
set hlsearch
set number
set expandtab
set tabstop=2
set shiftwidth=2
set autoindent
set smartindent
set cindent

syntax on

