name: Test install

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dotfiles
        run: ./install.sh
      - name: Check
        run: brew --version && sdk version && [ -d ~/.config ]
